# config/_default/languages.en.toml

title = "thoughts"
logo = "img/logo.png"
secondaryLogo = "img/logo-2.png"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  secondaryLogo = "img/logo-2.png"
  description = "My thoughts about life, which sometimes involves software."

[params.author]
name = "Carl Chesser"
image = "img/author.png"
headline = "My thoughts about life, which sometimes involves software."
bio = "lucky husband and father, software experimentalist, banjo apprentice, aspiring cartoonist, golden doodle whisperer"
links = [
  { x-twitter = "https://x.com/che55er" },
  { linkedin = "https://linkedin.com/in/carl-chesser" },
  { github = "https://github.com/cchesser" },
  { email = "mailto:cchesser@gmail.com" }
]
