baseurl = "https://che55er.io"
defaultContentLanguage = "en"
theme = "loveit"
title = "thoughts"
publishDir = "_deploy"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

[params]
  version = "0.2.X"
  # site default theme ("light", "dark", "auto")
  defaultTheme = "light"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/cchesser/che55er-site"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # date format
  dateFormat = "Jan _2, 2006"
  # website images for Open Graph and Twitter Cards
  images = ["img/avatar-icon.png"]

  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "auto"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/img/head.png"
      # title name
      name = "thoughts"
      # you can add extra information before the name (HTML format is supported), such as icons
      # pre = "<img src='/img/head.png' height='25' style='vertical-align:middle' />"
      # whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ''
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    # 是否显示版权信息
    copyright = false
    # whether to show the author
    author = false
    # site creation time
    since = 2018
    # license info (HTML format is supported)
    # license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "Jan _2"
    # amount of RSS pages
    rss = 10

  # List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Page config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false
    # whether to hide a page from search results
    hiddenFromSearch = false
    # whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # whether to enable the ruby extended syntax
    ruby = true
    # whether to enable the fraction extended syntax
    fraction = true
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = false
    # whether to show the full text content in RSS
    rssFullText = false
    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    # KaTeX mathematical formulas config (KaTeX https://katex.org/)
    [params.page.math]
      enable = false
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    # Social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Linkedin = true
      HackerNews = true
    # Comment config
    # 评论系统设置
    [params.page.comment]
      enable = true
      # Disqus comment config (https://disqus.com/)
      # Disqus 评论系统设置 (https://disqus.com/)
      [params.page.comment.disqus]
        enable = false
        # Disqus shortname to use Disqus in posts
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = ""
      # Gitalk comment config (https://github.com/gitalk/gitalk)
      # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.commento]
        enable = false
      # Utterances comment config (https://utteranc.es/)
    # Third-party library config
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/" 位于 "assets/"
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/" 位于 "assets/"
        # someJavascript = "https://cdn.example.com/some.js"
    # Page SEO config
    [params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = "Carl Chesser"
        logoUrl = "/images/avatar.png"

  # TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1


  # Site SEO config
  [params.seo]
    # image URL
    image = "/images/Apple-Devices-Preview.png"
    # thumbnail URL
    thumbnailUrl = "/images/screenshot.png"

  # Analytics config
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "UA-131402196-1"

[languages]
  [languages.en]
    weight = 1
    # language code
    languageCode = "en"
    # language name
    languageName = "English"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = false
    # default amount of posts in each pages
    paginate = 12
    # [UA-XXXXXXXX-X] google analytics code
    googleAnalytics = "UA-131402196-1"
    # copyright description used only for seo schema
    copyright = ""
    # Menu config
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = "<i class='fas fa-feather'></i> "
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "blog"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "series"
        pre = "<i class='fas fa-book'></i> "
        post = ""
        name = "series"
        url = "/blog-series/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "talks"
        pre = "<i class='fas fa-microphone'></i> "
        post = ""
        name = "talks"
        url = "/talks/"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "guides"
        pre = "<i class='fas fa-map'></i> "
        post = ""
        name = "guides"
        url = "/guides/"
        title = ""
        weight = 4
      [[languages.en.menu.main]]
        identifier = "articles"
        pre = "<i class='fas fa-newspaper'></i> "
        post = ""
        name = "articles"
        url = "/articles/"
        title = ""
        weight = 5
      [[languages.en.menu.main]]
        identifier = "projects"
        pre = "<i class='fas fa-drafting-compass'></i> "
        post = ""
        name = "projects"
        url = "/projects/"
        title = ""
        weight = 6
    [languages.en.params]
      # site description
      description = "thoughts of Carl Chesser"
      # site keywords
      keywords = ["Theme", "Hugo"]
      # App icon config
      [languages.en.params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        title = "thoughts"
        # whether to omit favicon resource links
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        svgFavicon = ""
        # Android browser theme color
        themeColor = "#ffffff"
        # Safari mask icon color
        iconColor = "#5bbad5"
        # Windows v8-10 tile color
        tileColor = "#da532c"
      # Search config
      [languages.en.params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "lunr"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
      # Home page config
      [languages.en.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = "cchesser@gmail.com"
          # URL of avatar shown in home page
          avatarURL = "/img/avatar-icon.png"
          # title shown in home page (HTML format is supported)
          title = "thoughts"
          # subtitle shown in home page
          subtitle = "My thoughts about life, which sometimes involves software."
          # whether to use typeit animation for subtitle
          typeit = false
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.en.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 6
      # Social config in home page
      [languages.en.params.social]
        GitHub = "cchesser"
        Linkedin = "carl-chesser"
        Twitter = "che55er"
        Email = "cchesser@gmail.com"
        RSS = true

# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "Carl Chesser"
  email = "cchesser@gmail.com"
  link = "https://che55er.io"

# Sitemap config
# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
